services:
  physics:
    build: { context: ., dockerfile: physics/Dockerfile }
    environment:
      ROBOREMOTE_PHYSICS_BIND_ADDR: "${ROBOREMOTE_PHYSICS_BIND_ADDR}"
      ROBOREMOTE_PHYSICS_PORT: "${ROBOREMOTE_PHYSICS_PORT}"

  server:
    build: { context: ., dockerfile: server/Dockerfile}
    environment:
      ROBOREMOTE_PHYSICS_ADDR: "physics:${ROBOREMOTE_PHYSICS_PORT}"
      ROBOREMOTE_SERVER_BIND_ADDR: "${ROBOREMOTE_SERVER_BIND_ADDR}"
    ports:
      - "${ROBOREMOTE_SERVER_PORT}:${ROBOREMOTE_SERVER_PORT}"
    depends_on:
      physics:
        condition: service_healthy

  tui:
    build: { context: ., dockerfile: tui/Dockerfile}
    environment:
      ROBOREMOTE_SERVER_ADDR: "server:${ROBOREMOTE_SERVER_PORT}"
    depends_on:
      - server
    stdin_open: true
    tty: true
    profiles: ["tui"]